#!/usr/bin/env python
#
# make_png_gcc
#    .png to .gcc GUI wrapper
# Basd on make_png_epi
#
# Neil Gershenfeld
# CBA MIT 1/24/11
# (c) Massachusetts Institute of Technology 2011
# Permission granted for experimental and personal use;
# license for commercial sale available from MIT.
# # Jon Nordby 9/1/14
# (c) Jon Nordby, Fellesverkstedet 2014

# imports
#
import wx,sys
from fab_set import fab_frame
from panel_control import control_panel
from panel_png import png_panel
from panel_png_path import png_path_panel
from panel_path_gcc import path_gcc_panel
#
# command line
#
print "command line: make_png_gcc [input_file [size]]"
print "   input_file = input .png file (optional)"
print "   size = image panel size (optional)"
#
# start wx
#
app = wx.App()
#
# add panels to frame
#
frame = fab_frame("make_png_gcc",sys.argv)
frame.control_panel = control_panel(frame)
frame.sizer.Add(frame.control_panel,(0,0),span=(1,3),flag=wx.ALIGN_CENTER_HORIZONTAL)
frame.gcc_panel = path_gcc_panel(frame)
frame.sizer.Add(frame.gcc_panel,(1,2))
frame.path_panel = png_path_panel(frame)
frame.sizer.Add(frame.path_panel,(1,1))
frame.png_panel = png_panel(frame)
frame.sizer.Add(frame.png_panel,(1,0))
#
# set defaults
#
frame.set_png_gcc()
#
# fit and show frame
#
frame.Fit()
frame.Show()
#
# start mainloop
#
app.MainLoop()
